### ISSUE TITLE
SpriteFrameCache::removeUnusedSpriteFrames doesn't work

### ISSUE THREAD

**Issue by halx99** [axis-project/axis#746]
Can't remove frames from cache, relative PR: #459 

```cpp
auto spriteFrameCache = SpriteFrameCache::getInstance();
spriteFrameCache->addSpriteFramesWithFile("ghosts.plist");
spriteFrameCache->removeUnusedSpriteFrames(); 
```

@rh101 Could you take a look about this issue?

**Comment by rh101** [comment]
Will do

**Comment by rh101** [comment]
No worries, I'll take a look at it now

**Comment by rh101** [comment]
Ok, so the issue has nothing to do with commit https://github.com/axis-project/axis/commit/4ad4bf93b0657d7bdeed9d69701e2614b621b5e8. That commit reduced the reference count from 3 to 2, which is great, but the issue doesn't come from there.

The issue is that the frames are auto-release objects, so when they are created, they have a reference of 1, like here:
```
SpriteFrame* SpriteFrame::createWithTexture(Texture2D* texture,
                                            const Rect& rect,
                                            bool rotated,
                                            const Vec2& offset,
                                            const Vec2& originalSize)
{
    SpriteFrame* spriteFrame = new SpriteFrame();
    if (spriteFrame->initWithTexture(texture, rect, rotated, offset, originalSize))
    {
        spriteFrame->autorelease();
        return spriteFrame;
    }

    delete spriteFrame;
    return nullptr;
}
```

When they're added to the cache, the reference count increases to 2.

On the next update loop, the auto-release code will decrease all frame references by 1, so they will all be equal to 1.

This works to clear the frames, since it calls it on the next loop, after the auto-release code has run:
    auto spriteFrameCache = SpriteFrameCache::getInstance();
    spriteFrameCache->addSpriteFramesWithFile("ghosts.plist");

    scheduleOnce(
        [spriteFrameCache](float) {
            spriteFrameCache->removeUnusedSpriteFrames();
        }, 0.0f, "CLEAR_FRAMES");

This issue is in the cocos2d engine as well, and it seems that it's always been this way.

Loading them removing the frames within the same loop isn't a typical use-case, but it be good to fix it, since it will mean less code to write in order to clear the frames, and no need to wait till the next loop.

Now, a problem.  On the current loop, ref = 2, but on the next loop, ref = 1.  We can't check for ref = 2 in the `SpriteFrameCache::removeUnusedSpriteFrames()` method, since we don't know if it's in auto-release or not.  We can probably do this:

```
if (spriteFrame->getReferenceCount() == 1 || (spriteFrame->getReferenceCount() == 2 && poolManager->isObjectInPools(this)))
{
    toRemoveFrames.push_back(iter.first);
    spriteFrame->getTexture()->removeSpriteFrameCapInset(spriteFrame);
    CCLOG("cocos2d: SpriteFrameCache: removing unused frame: %s", iter.first.c_str());
    removed = true;
}
```

But, I'm not sure what kind of performance impact this may have, since it's checking for the object in the pool for every single frame.  The more frames, and the more objects in the pool, the slower it will be.

The alternative is removing the object from the auto-release pool, but no method exists to remove it in the `AutoreleasePool` class.  It only has `addObject()` and `contains()`, but what do you think if we add `removeObject`?

We can then call `AutoreleasePool::removeObject(spriteFrame)` before adding it to the cache, so the reference will be 1, like this:

```
void PlistSpriteSheetLoader::addSpriteFramesWithDictionary(ValueMap& dictionary,
                                                           Texture2D* texture,
                                                           std::string_view plist,
                                                           SpriteFrameCache& cache)
{
...
            spriteFrame = SpriteFrame::createWithTexture(texture, Rect(x, y, w, h), false, Vec2(ox, oy),
                                                         Vec2((float)ow, (float)oh));

...
        // add sprite frame
        PoolManager::getInstance()->getCurrentPool()->removeObject(spriteFrame);
        cache.insertFrame(spriteSheet, spriteFrameName, spriteFrame);

...
}
```

The other option is adding new `SpriteFrame::createXXXXXX` methods that do not add frames to the auto-release pool, or maybe just add a parameter to the existing methods named `autorelease`, with default value of `true`, like this:
```
SpriteFrame* SpriteFrame::create(std::string_view filename,
                                 const Rect& rect,
                                 bool rotated,
                                 const Vec2& offset,
                                 const Vec2& originalSize,
                                 bool autorelease = true)
{
    SpriteFrame* spriteFrame = new SpriteFrame();
    if (spriteFrame->initWithTextureFilename(filename, rect, rotated, offset, originalSize))
    {
        if (autorelease) {
            spriteFrame->autorelease();
        }
        return spriteFrame;
    }
    delete spriteFrame;
    return nullptr;
}
```

Which do you prefer, or do you have any ideas on how else we could deal with this?

**Comment by halx99** [comment]
I think it's ok current behavior same with cocos2dx
